export default {
  poppinsBlack: 'Poppins-Black',
  poppinsBlackItalic: 'Poppins-BlackItalic',
  poppinsBold: 'Poppins-Bold',
  poppinsBoldItalic: 'Poppins-BoldItalic',
  poppinsExtraBold: 'Poppins-ExtraBold',
  poppinsExtraBoldItalic: 'Poppins-ExtraBoldItalic',
  poppinsExtraLight: 'Poppins-ExtraLight',
  poppins_talic: 'Poppins-Italic',
  poppinsLight: 'Poppins-Light',
  poppinsLightItalic: 'Poppins-LightItalic',
  poppinsMedium: 'Poppins-Medium',
  poppinsMediumItalic: 'Poppins-MediumItalic',
  poppinsRegular: 'Poppins-Regular',
  poppinsSemiBold: 'Poppins-SemiBold',
  poppinsSemiBoldItalic: 'Poppins-SemiBoldItalic',
  poppinsThin: 'Poppins-Thin',
  poppinsThinItalic: 'Poppins-ThinItalic',
};
